"""initial

Revision ID: 1730420a49bf
Revises: 
Create Date: 2024-10-13 17:37:51.858795

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1730420a49bf"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("admin_id", sa.Integer(), nullable=False),
        sa.Column("add_tb", sa.Boolean(), nullable=False),
        sa.Column("edit_tb", sa.Boolean(), nullable=False),
        sa.Column("del_tb", sa.Boolean(), nullable=False),
        sa.Column("add_time", sa.Boolean(), nullable=False),
        sa.Column("edit_time", sa.Boolean(), nullable=False),
        sa.Column("del_time", sa.Boolean(), nullable=False),
        sa.Column("add_source", sa.Boolean(), nullable=False),
        sa.Column("edit_source", sa.Boolean(), nullable=False),
        sa.Column("del_source", sa.Boolean(), nullable=False),
        sa.Column("rerate", sa.Boolean(), nullable=False),
        sa.Column("comments", sa.Boolean(), nullable=False),
        sa.Column("event", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("admin_id"),
    )
    op.create_table(
        "events",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("source", sa.JSON(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "thematic_blocks",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("source", sa.JSON(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "publications",
        sa.Column("time", sa.String(), nullable=False),
        sa.Column("thematic_block_id", sa.Integer(), nullable=False),
        sa.Column("today", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(
            ["thematic_block_id"],
            ["thematic_blocks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("publications")
    op.drop_table("thematic_blocks")
    op.drop_table("events")
    op.drop_table("admins")
    # ### end Alembic commands ###
